<?php
/**
* Skip Checkout Login
* https://github.com/koenberkhout/Magento-Skip-Checkout-Login-Step-1
*
* @author    Koen Berkhout
* @copyright (c) Koen Berkhout - All rights reserved.
*/
?>

<?php if (Mage::getStoreConfig('skipcheckoutlogin_section/skipcheckoutlogin_group/skipcheckoutlogin_enable')): ?>

    <?php $checkoutMethod = Mage::getSingleton('checkout/type_onepage')->getCheckoutMethod(); ?>
    <?php if ($checkoutMethod == 'guest'): ?>
        <script type="text/javascript">
            var child = document.getElementById("register-customer-password");
            child.parentNode.removeChild(child);
        </script>
    <?php endif; ?>

<?php endif; ?>